# 오늘의 목표는 이렇습니다
- 오늘은 참여형이라기보다, 흥미유발형으로
- 주식 초보인 우리가 주식투자전략을 시뮬레이션하는 시스템을 구축하고,
- 여기에 간단한 아이디어를 검증 해보는 것을 목표로 합니다.
- 다음 시간에는, 참여형으로 여러분의 아이디어를 검증하는 것을 목표로!

## 아니 근데 대관절 왠 주식투자?
- 이게 참으로 데이터 사이언스 하기 좋은 주제
- 판다스가 나옴, 괴물같은 모습으로!

## 오늘의 참고자료
- [슈카형이 설명하는 주식지표와 워렌버핏 가치투자](https://youtu.be/uhqFaT0YI1w)
- [주식용어정리 1편 - ROE, PER, PBR](https://m.blog.naver.com/lifadviser/221276226054)
- [Naver Finance 국내증시 Data 수집](https://jsp-dev.tistory.com/entry/PythonBS4-Naver-Finance-%EA%B5%AD%EB%82%B4-%EC%A6%9D%EC%8B%9C-%EA%B8%B0%EC%B4%88-Data-%EC%88%98%EC%A7%91)

In [232]:
import pandas as pd

In [256]:
import requests

nhn_url = 'https://finance.naver.com/sise/field_submit.nhn' \
    '?menu=market_sum' \
    '&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page={}' \
    '&fieldIds=market_sum' \
    '&fieldIds=operating_profit' \
    '&fieldIds=open_val' \
    '&fieldIds=property_total' \
    '&fieldIds=debt_total' \
    '&fieldIds=listed_stock_cnt'

res = requests.get(nhn_url.format(1))

In [257]:
df3 = pd.read_html(res.text)

In [258]:

df4 = df3[1][ df3[1]['N'].notna()]
df4.head()

,N,종목명,현재가,전일비,등락률,액면가,시가,상장주식수,시가총액,자산총계,부채총계,영업이익,토론실
1,1.0,삼성전자,54900.0,600.0,-1.08%,100.0,56400.0,5969783.0,3277411.0,3525645.0,896841.0,277685.0,NaN
2,2.0,SK하이닉스,91000.0,600.0,+0.66%,5000.0,93000.0,728002.0,662482.0,647895.0,168463.0,27127.0,NaN
3,3.0,삼성바이오로직스,664000.0,1000.0,-0.15%,2500.0,667000.0,66165.0,439336.0,59116.0,15572.0,917.0,NaN
4,4.0,NAVER,240500.0,9500.0,+4.11%,100.0,234500.0,164263.0,395053.0,122995.0,57956.0,7101.0,NaN
5,5.0,삼성전자우,47800.0,50.0,+0.10%,100.0,49000.0,822887.0,393340.0,NaN,NaN,NaN,NaN

In [259]:
df5 = df4.loc[:, ['N', '종목명', '현재가', '시가', '상장주식수', '시가총액', '자산총계', '부채총계', '영업이익']]
df5['N'] = df5['N'].astype('int')
df5.index = df5['N']
df5 = df5.drop(axis=1, columns='N')
df5.tail()

,종목명,현재가,시가,상장주식수,시가총액,자산총계,부채총계,영업이익
N,,,,,,,,
46,오리온,129500.0,131500.0,39536.0,51199.0,24523.0,7848.0,3276.0
47,아모레G,59300.0,60300.0,82458.0,48898.0,82814.0,18012.0,4982.0
48,현대글로비스,124500.0,127000.0,37500.0,46688.0,101297.0,54595.0,8765.0
49,미래에셋대우,7080.0,7280.0,658316.0,46609.0,1331498.0,1239562.0,7280.0
50,LG디스플레이,12750.0,12450.0,357816.0,45622.0,355746.0,230863.0,-13594.0

In [260]:
naverfin = df5

num_total = 32


encoded_url = 'https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn%3F%26page%3D{}&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt'


for i in range(2, num_total+1):
    
    print(nhn_url.format(i))
    res = requests.get(encoded_url.format(i))
    
    tmp_df = pd.read_html(res.text)
    #print(tmp_df[1].columns)

    tmp_df = tmp_df[1][tmp_df[1]['N'].notna()].loc[:, ['N', '종목명', '현재가', '시가', '상장주식수', '시가총액', '자산총계', '부채총계', '영업이익']]
    
    
    tmp_df['N'] = tmp_df['N'].astype('int')
    tmp_df.index = tmp_df['N']
    tmp_df = tmp_df.drop(axis=1, columns='N')
    print(tmp_df.head())
    
    naverfin = naverfin.append(tmp_df)
    
naverfin.shape

https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=2&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
        종목명       현재가        시가     상장주식수     시가총액      자산총계      부채총계    영업이익
N
51  현대중공업지주  286000.0  289000.0   15799.0  45184.0  257155.0  138308.0  6666.0
52   CJ제일제당  297500.0  300500.0   15054.0  44786.0  262806.0  167992.0  8969.0
53    삼성중공업    6990.0    6930.0  630000.0  44037.0  136001.0   83512.0 -6166.0
54     현대건설   36700.0   37750.0  111356.0  40868.0  182270.0   95120.0  8597.0
55   맥쿼리인프라   11650.0   11700.0  349044.0  40664.0       NaN       NaN     NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=3&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                  종목명       현재가        시가     상장주식수     시가총액      자산총계  \
N
101                한샘   89200.0   92300.0   23534.0  20992.0   12026.0
102               오뚜기  581000.0  576000.0    3605.0  20946.0   21521.0
103  KODEX 200선물인버스2X    5075.0    4880.0  407800.0  20696.0       NaN
104              제일기획   17950.0   18500.0  115041.0  20650.0   22528.0
105              키움증권   90600.0   93500.0   22100.0  20022.0  233736.0

         부채총계    영업이익
N
101    5893.0   558.0
102    8056.0  1483.0
103       NaN     NaN
104   12960.0  2058.0
105  211152.0  4737.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=4&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
            종목명      현재가       시가    상장주식수     시가총액     자산총계     부채총계    영업이익
N
151         파미셀  21150.0  21500.0  59959.0  12681.0    633.0    117.0    20.0
152  KBSTAR 200  29090.0  29605.0  42650.0  12407.0      NaN      NaN     NaN
153      더블유게임즈  67200.0  64900.0  18266.0  12274.0  10747.0   4276.0  1546.0
154       두산솔루스  40000.0  41000.0  30590.0  12236.0   4942.0   3536.0   102.0
155        태영건설  15850.0  15600.0  76400.0  12109.0  59161.0  43447.0  3912.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=5&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                종목명       현재가        시가    상장주식수    시가총액      자산총계      부채총계  \
N
201              두산   49250.0   45950.0  16524.0  8138.0  291697.0  223502.0
202              후성    8760.0    8800.0  92607.0  8112.0    5289.0    2860.0
203            롯데제과  126000.0  127000.0   6417.0  8085.0   27162.0   14154.0
204          JW중외제약   38450.0   39000.0  20920.0  8044.0    5732.0    3431.0
205  KODEX 단기채권PLUS  102530.0  102535.0   7805.0  8002.0       NaN       NaN

        영업이익
N
201  12619.0
202    134.0
203    973.0
204   -190.0
205      NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=6&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
         종목명       현재가        시가    상장주식수    시가총액     자산총계     부채총계    영업이익
N
251    효성티앤씨  132500.0  133000.0   4328.0  5734.0  32243.0  26414.0  3229.0
252       서흥   49300.0   50200.0  11569.0  5704.0   7089.0   3799.0   474.0
253  SK디스커버리   29800.0   30200.0  19038.0  5673.0  50001.0  26769.0  1739.0
254      풀무원   14850.0   14850.0  38091.0  5656.0  14846.0  10215.0   306.0
255    경동나비엔   42950.0   44000.0  12740.0  5472.0   6098.0   3088.0   448.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=7&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
               종목명      현재가       시가    상장주식수    시가총액     자산총계     부채총계   영업이익
N
301          일진다이아  29250.0  28800.0  14203.0  4154.0   2491.0    645.0  132.0
302           광동제약   7840.0   7850.0  52421.0  4110.0   7928.0   3453.0  418.0
303             LF  14000.0  14200.0  29240.0  4094.0  24171.0  10256.0  875.0
304  TIGER 단기채권액티브  50370.0  50370.0   8096.0  4078.0      NaN      NaN    NaN
305    KOSEF 200TR  33765.0  34305.0  12050.0  4069.0      NaN      NaN    NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=8&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
              종목명       현재가        시가     상장주식수    시가총액     자산총계     부채총계  \
N
351         한국쉘석유  264000.0  265000.0    1300.0  3432.0   1411.0    432.0
352           쌍용차    2290.0    1965.0  149840.0  3431.0  20192.0  16161.0
353  TIGER 200 IT   24425.0   24560.0   14020.0  3424.0      NaN      NaN
354       유나이티드제약   21000.0   20000.0   16232.0  3409.0   3312.0    761.0
355  HANARO 단기통안채  102615.0  102615.0    3299.0  3385.0      NaN      NaN

       영업이익
N
351   257.0
352 -2819.0
353     NaN
354   345.0
355     NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=9&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                       종목명      현재가       시가     상장주식수    시가총액     자산총계  \
N
401             아모레G3우(전환)  36700.0  36750.0    7092.0  2603.0      NaN
402                     E1  37850.0  37800.0    6860.0  2597.0  35950.0
403              SBS미디어홀딩스   1855.0   1850.0  139896.0  2595.0   6741.0
404                    케이씨  19050.0  19300.0   13554.0  2582.0   6805.0
405  삼성 인버스 2X 천연가스 선물 ETN  25575.0  25735.0   10000.0  2558.0      NaN

        부채총계    영업이익
N
401      NaN     NaN
402  23917.0  1063.0
403    736.0    48.0
404   1732.0   676.0
405      NaN     NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=10&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                         종목명      현재가       시가    상장주식수    시가총액    자산총계  \
N
451                    한국주철관   9470.0   9510.0  22800.0  2159.0  3520.0
452                  넥스트사이언스   6780.0   7150.0  31800.0  2156.0  1294.0
453                     한국철강   4665.0   4800.0  46050.0  2148.0  8732.0
454  TIGER 차이나CSI300레버리지(합성)  19340.0  19325.0  11100.0  2147.0     NaN
455                     동부건설   9760.0  10100.0  21877.0  2135.0  8919.0

       부채총계   영업이익
N
451   831.0   66.0
452   475.0  -44.0
453  1483.0  122.0
454     NaN    NaN
455  4713.0  555.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=11&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                         종목명      현재가       시가    상장주식수    시가총액    자산총계  \
N
501    QV 코스피 양매도 5% OTM ETN   8815.0   8815.0  20000.0  1763.0     NaN
502                   종근당바이오  32050.0  32100.0   5486.0  1758.0  2333.0
503             TIGER 중국소비테마   7065.0   6960.0  24690.0  1744.0     NaN
504      KBSTAR 코스닥150선물레버리지  10410.0  10465.0  16740.0  1743.0     NaN
505  TIGER 글로벌4차산업혁신기술(합성 H)  13310.0  13305.0  12900.0  1717.0     NaN

      부채총계   영업이익
N
501    NaN    NaN
502  749.0  154.0
503    NaN    NaN
504    NaN    NaN
505    NaN    NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=12&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
         종목명     현재가      시가     상장주식수    시가총액    자산총계    부채총계   영업이익
N
551     아남전자  1970.0  1980.0   77125.0  1519.0  1465.0   888.0   31.0
552       신원  1780.0  1810.0   85042.0  1514.0  4034.0  2019.0   90.0
553  NH투자증권우  7980.0  8010.0   18871.0  1506.0     NaN     NaN    NaN
554       DB   748.0   752.0  201174.0  1505.0  3632.0  1522.0  185.0
555   이수페타시스  3635.0  3685.0   41268.0  1500.0  4167.0  3407.0 -240.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=13&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
       종목명       현재가        시가     상장주식수    시가총액    자산총계    부채총계   영업이익
N
601   국제약품    7170.0    7170.0   18401.0  1319.0  1346.0   736.0   56.0
602    BYC  211000.0  214500.0     625.0  1318.0  6939.0  2596.0  234.0
603   화성산업   10550.0   10700.0   12451.0  1314.0  6126.0  2416.0  296.0
604  사조동아원     929.0     924.0  141145.0  1311.0  4669.0  2699.0  125.0
605    STX    6640.0    6690.0   19727.0  1310.0  5601.0  5038.0   17.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=14&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                          종목명      현재가       시가    상장주식수    시가총액     자산총계  \
N
651  TIGER 미국S&P500레버리지(합성 H)  18200.0  18195.0   6200.0  1128.0      NaN
652                        국동   3175.0   3230.0  35302.0  1121.0   1333.0
653                       유니켐   1655.0   1605.0  67672.0  1120.0   1697.0
654                    인천도시가스  25500.0  25600.0   4375.0  1116.0   3653.0
655                      제주은행   3450.0   3490.0  32129.0  1108.0  61929.0

        부채총계   영업이익
N
651      NaN    NaN
652    688.0  -42.0
653    810.0  179.0
654   1803.0  120.0
655  56952.0  372.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=15&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
            종목명      현재가       시가    상장주식수   시가총액     자산총계     부채총계   영업이익
N
701        한양증권   7500.0   7620.0  12729.0  955.0  18222.0  15275.0  296.0
702       우리들제약   6940.0   6880.0  13706.0  951.0   1000.0    438.0   12.0
703  현대코퍼레이션홀딩스  10450.0  10700.0   9101.0  951.0   2414.0    619.0   93.0
704        기신정기   3255.0   3255.0  29200.0  950.0   2458.0    121.0  103.0
705       콤텍시스템   1400.0   1435.0  67851.0  950.0   1615.0    666.0   30.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=16&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                          종목명      현재가       시가    상장주식수   시가총액    자산총계  \
N
751  KBSTAR 미국S&P원유생산기업(합성 H)   2910.0   2795.0  28950.0  842.0     NaN
752                       다스코   5470.0   5540.0  15400.0  842.0  2147.0
753                      사조오양   8930.0   8700.0   9423.0  841.0  3112.0
754                       시디즈  42000.0  42000.0   2000.0  840.0   671.0
755                      화천기계   3790.0   3920.0  22000.0  834.0  1583.0

       부채총계   영업이익
N
751     NaN    NaN
752   914.0   31.0
753  1436.0  226.0
754   350.0   86.0
755   337.0  -93.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=17&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                     종목명      현재가       시가    상장주식수   시가총액    자산총계   부채총계  \
N
801  TIGER 유로스탁스50(합성 H)  11385.0  11420.0   6300.0  717.0     NaN    NaN
802                유양디앤유   1220.0      0.0  58494.0  714.0  2069.0  914.0
803  신한 레버리지 은 선물 ETN(H)   7090.0   6875.0  10000.0  709.0     NaN    NaN
804                 화천기공  32150.0  32600.0   2200.0  707.0  3749.0  783.0
805                 대원화성   1710.0   1790.0  41249.0  705.0  1305.0  511.0

     영업이익
N
801   NaN
802 -51.0
803   NaN
804  69.0
805  67.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=18&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
               종목명       현재가        시가     상장주식수   시가총액    자산총계    부채총계   영업이익
N
851  KBSTAR 금융채액티브  102190.0  102185.0     570.0  582.0     NaN     NaN    NaN
852         상신브레이크    2710.0    2700.0   21471.0  582.0  4523.0  2754.0  157.0
853           서울식품     172.0     171.0  337410.0  580.0   760.0   510.0    4.0
854         SK케미칼우   39700.0   39500.0    1459.0  579.0     NaN     NaN    NaN
855        미래에셋대우우    4100.0    4075.0   14076.0  577.0     NaN     NaN    NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=19&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                  종목명      현재가       시가    상장주식수   시가총액    자산총계    부채총계   영업이익
N
901              대동전자   4495.0   4450.0  10490.0  472.0  1710.0   331.0   -2.0
902  대신 철광석 선물 ETN(H)  23490.0  22585.0   2000.0  470.0     NaN     NaN    NaN
903             평화홀딩스   3210.0   3290.0  14625.0  469.0  5029.0  3789.0  -36.0
904              태양금속   1270.0   1255.0  36700.0  466.0  3937.0  3220.0 -176.0
905            한국종합기술   4235.0   4195.0  10950.0  464.0  2759.0  1803.0  -21.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=20&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                       종목명       현재가        시가    상장주식수   시가총액    자산총계  \
N
951                    코아스    1220.0    1260.0  30907.0  377.0   773.0
952  신한 인버스 천연가스 선물 ETN(H)   18755.0   18835.0   2000.0  375.0     NaN
953           KBSTAR 국고채3년  113605.0  113505.0    330.0  375.0     NaN
954           KOSEF 코스닥150    5870.0    5895.0   6380.0  374.0     NaN
955                   이화산업   13350.0   13300.0   2800.0  374.0  2827.0

       부채총계  영업이익
N
951   520.0  31.0
952     NaN   NaN
953     NaN   NaN
954     NaN   NaN
955  1048.0 -17.0
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=21&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                         종목명       현재가        시가     상장주식수   시가총액    자산총계  \
N
1001        KINDEX 중장기국공채액티브  103250.0  103220.0     293.0  303.0     NaN
1002                    흥아해운     258.0       0.0  116733.0  301.0  4310.0
1003                 하이골드12호    2300.0    2300.0   13044.0  300.0   364.0
1004     TIGER 일본TOPIX(합성 H)   13555.0   13440.0    2200.0  298.0     NaN
1005  삼성 China A50 선물 ETN(H)   14880.0   14835.0    2000.0  298.0     NaN

        부채총계   영업이익
N
1001     NaN    NaN
1002  4000.0 -124.0
1003    70.0   54.0
1004     NaN    NaN
1005     NaN    NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=22&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                     종목명      현재가       시가   상장주식수   시가총액  자산총계  부채총계  영업이익
N
1051   ARIRANG KS로우볼가중TR  10225.0  10440.0  2400.0  245.0   NaN   NaN   NaN
1052  미래에셋 유럽 중형주 ETN(H)  12260.0  12225.0  2000.0  245.0   NaN   NaN   NaN
1053      ARIRANG 단기우량채권  53105.0  53105.0   460.0  244.0   NaN   NaN   NaN
1054           TIGER 로우볼   9835.0   9850.0  2480.0  244.0   NaN   NaN   NaN
1055  KODEX 미국FANG플러스(H)  16130.0  15930.0  1500.0  242.0   NaN   NaN   NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=23&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                    종목명      현재가       시가   상장주식수   시가총액   자산총계   부채총계  영업이익
N
1101               세기상사  51300.0  51900.0   408.0  209.0  416.0  191.0  -5.0
1102     TIGER 200 헬스케어  24175.0  24055.0   860.0  208.0    NaN    NaN   NaN
1103      HANARO KRX300  13405.0  13620.0  1550.0  208.0    NaN    NaN   NaN
1104  삼성 미국 중소형 가치주 ETN  10345.0  10275.0  2000.0  207.0    NaN    NaN   NaN
1105           하이트진로2우B  18250.0  18450.0  1130.0  206.0    NaN    NaN   NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=24&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                        종목명      현재가       시가   상장주식수   시가총액   자산총계   부채총계  \
N
1151      TIGER 미국달러선물인버스2X   8790.0   8815.0  2000.0  176.0    NaN    NaN
1152  KODEX 글로벌4차산업로보틱스(합성)  13000.0  12920.0  1350.0  176.0    NaN    NaN
1153   신한 코스피 콘도르 4/10% ETN   8675.0   8675.0  2000.0  174.0    NaN    NaN
1154                   하이트론   3115.0   3290.0  5531.0  172.0  556.0  385.0
1155   KODEX 미국채울트라30년선물(H)  13070.0  13055.0  1300.0  170.0    NaN    NaN

       영업이익
N
1151    NaN
1152    NaN
1153    NaN
1154 -153.0
1155    NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=25&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                            종목명      현재가       시가   상장주식수   시가총액  자산총계  부채총계  \
N
1201  SMART 선진국MSCI World(합성 H)  13875.0  14090.0  1000.0  139.0   NaN   NaN
1202         KODEX 미국S&P에너지(합성)   6295.0   6280.0  2194.0  138.0   NaN   NaN
1203       QV 미국 IT TOP5 ETN(H)  19650.0  19650.0   700.0  138.0   NaN   NaN
1204                KBSTAR 채권혼합  57145.0  57350.0   240.0  137.0   NaN   NaN
1205               KODEX 코스피100  22645.0  23000.0   600.0  136.0   NaN   NaN

      영업이익
N
1201   NaN
1202   NaN
1203   NaN
1204   NaN
1205   NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=26&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                         종목명      현재가       시가   상장주식수   시가총액  자산총계  부채총계  \
N
1251                 SK네트웍스우  98500.0  87400.0   114.0  112.0   NaN   NaN
1252  미래에셋 인버스 S&P500 ETN(H)   5565.0   5690.0  2000.0  111.0   NaN   NaN
1253     KODEX S&P글로벌인프라(합성)  11125.0  11025.0   997.0  111.0   NaN   NaN
1254                   코리아써우   3730.0   3695.0  2965.0  111.0   NaN   NaN
1255                   계양전기우   7880.0   7500.0  1400.0  110.0   NaN   NaN

      영업이익
N
1251   NaN
1252   NaN
1253   NaN
1254   NaN
1255   NaN
https://finance.naver.com/sise/field_submit.nhn?menu=market_sum&returnUrl=http%3A%2F%2Ffinance.naver.com%2Fsise%2Fsise_market_sum.nhn?&page=27&fieldIds=market_sum&fieldIds=operating_profit&fieldIds=open_val&fieldIds=property_total&fieldIds=debt_total&fieldIds=listed_stock_cnt
                                종목명      현재가       시가   상장주식수  시가총액  자산총계  \
N

(1557, 8)

In [262]:
naverfin

,종목명,현재가,시가,상장주식수,시가총액,자산총계,부채총계,영업이익
N,,,,,,,,
1,삼성전자,54900.0,56400.0,5969783.0,3277411.0,3525645.0,896841.0,277685.0
2,SK하이닉스,91000.0,93000.0,728002.0,662482.0,647895.0,168463.0,27127.0
3,삼성바이오로직스,664000.0,667000.0,66165.0,439336.0,59116.0,15572.0,917.0
4,NAVER,240500.0,234500.0,164263.0,395053.0,122995.0,57956.0,7101.0
5,삼성전자우,47800.0,49000.0,822887.0,393340.0,NaN,NaN,NaN
6,셀트리온,256000.0,260500.0,134939.0,345445.0,38937.0,9867.0,3781.0
7,LG화학,434000.0,440000.0,70592.0,306371.0,340244.0,166406.0,8956.0
8,삼성SDI,375500.0,376000.0,68765.0,258211.0,198521.0,71918.0,4622.0
9,현대차,113000.0,114000.0,213668.0,241445.0,1945122.0,1181465.0,36055.0
10,카카오,256500.0,252500.0,87159.0,223563.0,87373.0,29971.0,2068.0
11,LG생활건강,1379000.0,1415000.0,15618.0,215375.0,64937.0,22566.0,11764.0
12,삼성물산,113500.0,114500.0,186887.0,212117.0,459055.0,192134.0,8668.0
13,현대모비스,217500.0,225000.0,95055.0,206744.0,466061.0,141964.0,23593.0
14,SK,257000.0,264000.0,70360.0,180826.0,1320207.0,798380.0,39499.0
15,SK텔레콤,222500.0,225500.0,80746.0,179659.0,446116.0,217881.0,11100.0
16,POSCO,202500.0,204500.0,87187.0,176553.0,790587.0,312640.0,38689.0
17,엔씨소프트,797000.0,809000.0,21954.0,174974.0,33464.0,8342.0,4790.0
18,신한지주,34750.0,36000.0,482432.0,167645.0,5524196.0,5104892.0,50463.0
19,KB금융,38200.0,39400.0,415808.0,158839.0,5185381.0,4794188.0,44906.0
20,기아차,37450.0,37250.0,405363.0,151809.0,553448.0,263667.0,20097.0
21,한국전력,22200.0,22550.0,641964.0,142516.0,1975978.0,1287081.0,-12765.0
22,삼성에스디에스,183000.0,186000.0,77378.0,141601.0,90212.0,22961.0,9901.0
23,LG,72500.0,75900.0,172557.0,125104.0,224346.0,34136.0,10241.0
24,KT&G,88000.0,89100.0,137292.0,120817.0,107121.0,20062.0,13820.0
25,SK이노베이션,126500.0,131500.0,92466.0,116969.0,395261.0,213164.0,12693.0
26,LG전자,64000.0,64500.0,163648.0,104735.0,448599.0,284347.0,24361.0
27,아모레퍼시픽,179000.0,178500.0,58458.0,104641.0,59890.0,14902.0,4278.0
28,삼성생명,50600.0,51500.0,200000.0,101200.0,3127623.0,2754459.0,12526.0
29,삼성전기,130000.0,133500.0,74694.0,97102.0,86742.0,32442.0,7340.0
30,삼성화재,198500.0,206000.0,47375.0,94039.0,851722.0,708507.0,8626.0
...,...,...,...,...,...,...,...,...
1528,신원우,39200.0,38750.0,91.0,36.0,NaN,NaN,NaN
1529,KBSTAR 코스닥150선물인버스,6390.0,6385.0,550.0,35.0,NaN,NaN,NaN
1530,유유제약2우B,21400.0,21200.0,164.0,35.0,NaN,NaN,NaN
1531,TIGER 은행,6040.0,6130.0,580.0,35.0,NaN,NaN,NaN
1532,TIGER 200 산업재,4275.0,4390.0,800.0,34.0,NaN,NaN,NaN
1533,노루홀딩스우,18250.0,18300.0,185.0,34.0,NaN,NaN,NaN
1534,마이티 코스피고배당,10165.0,10170.0,330.0,34.0,NaN,NaN,NaN
1535,KBSTAR 수출주,8360.0,8380.0,400.0,33.0,NaN,NaN,NaN
1536,KBSTAR 팔라듐선물인버스(H),6475.0,6515.0,500.0,32.0,NaN,NaN,NaN
1537,동양우,5170.0,5210.0,618.0,32.0,NaN,NaN,NaN
1538,동양2우B,10350.0,10000.0,309.0,32.0,NaN,NaN,NaN
1539,KBSTAR 200커뮤니케이션서비스,13225.0,13125.0,240.0,32.0,NaN,NaN,NaN
1540,KBSTAR 200중공업,7915.0,7965.0,400.0,32.0,NaN,NaN,NaN
1541,ARIRANG KRX300헬스케어,11575.0,11615.0,260.0,30.0,NaN,NaN,NaN
1542,파워 스마트밸류,11790.0,11985.0,250.0,29.0,NaN,NaN,NaN
1543,KBSTAR 미국장기국채선물인버스2X(합성 H),5860.0,6000.0,500.0,29.0,NaN,NaN,NaN
1544,TIGER 대만TAIEX선물(H),14630.0,14700.0,200.0,29.0,NaN,NaN,NaN
1545,KBSTAR 중소형모멘텀로우볼,8320.0,8425.0,350.0,29.0,NaN,NaN,NaN
1546,동양3우B,31050.0,30900.0,90.0,28.0,NaN,NaN,NaN
1547,KBSTAR 200경기소비재,7710.0,7745.0,360.0,28.0,NaN,NaN,NaN
1548,KINDEX 필리핀MSCI(합성),13420.0,13410.0,200.0,27.0,NaN,NaN,NaN
1549,TIGER 금속선물(H),4385.0,4365.0,600.0,26.0,NaN,NaN,NaN
1550,KBSTAR 200철강소재,5840.0,5875.0,440.0,26.0,NaN,NaN,NaN
1551,KBSTAR 200에너지화학,7785.0,7900.0,320.0,25.0,NaN,NaN,NaN
1552,KBSTAR 200건설,8370.0,8485.0,260.0,22.0,NaN,NaN,NaN
1553,TREX 중소형가치,6735.0,6790.0,300.0,20.0,NaN,NaN,NaN
1554,KBSTAR 200금융,6960.0,7060.0,280.0,19.0,NaN,NaN,NaN
1555,TIGER 원유선물인버스(H),12010.0,11935.0,150.0,18.0,NaN,NaN,NaN
1556,TIGER 코스닥150로우볼,12540.0,12540.0,140.0,18.0,NaN,NaN,NaN
1557,KBSTAR 200산업재,7820.0,7935.0,140.0,11.0,NaN,NaN,NaN

In [266]:
naverfin[81:100]

,종목명,현재가,시가,상장주식수,시가총액,자산총계,부채총계,영업이익
N,,,,,,,,
82,쌍용양회,5400.0,5480.0,503860.0,27208.0,33288.0,15263.0,2284.0
83,삼성엔지니어링,13650.0,13800.0,196000.0,26754.0,45452.0,32424.0,3855.0
84,휠라홀딩스,43800.0,43700.0,60752.0,26609.0,37702.0,19693.0,4707.0
85,CJ,91100.0,92300.0,29177.0,26580.0,403814.0,257663.0,15092.0
86,BGF리테일,151500.0,156500.0,17284.0,26185.0,21724.0,15498.0,1966.0
87,롯데쇼핑,92300.0,94500.0,28289.0,26111.0,339726.0,220709.0,4279.0
88,하이트진로,37150.0,38050.0,70134.0,26055.0,32709.0,22377.0,882.0
89,한국항공우주,26600.0,27200.0,97475.0,25928.0,43671.0,31840.0,2756.0
90,현대차2우B,71000.0,69200.0,36485.0,25905.0,NaN,NaN,NaN
91,신세계,251000.0,256500.0,9845.0,24711.0,130185.0,75034.0,4678.0
92,금호석유,77900.0,78800.0,30468.0,23734.0,45380.0,19085.0,3678.0
93,GS건설,29250.0,29850.0,80098.0,23429.0,131712.0,90282.0,7673.0
94,현대해상,26000.0,26450.0,89400.0,23244.0,463938.0,418834.0,3953.0
95,한미사이언스,34200.0,33500.0,66011.0,22576.0,9108.0,2651.0,380.0
96,메리츠증권,3580.0,3720.0,617311.0,22100.0,381099.0,340907.0,6799.0
97,SKC,58400.0,59300.0,37535.0,21920.0,39730.0,22466.0,1551.0
98,일진머티리얼즈,47450.0,48400.0,46111.0,21880.0,10369.0,2127.0,469.0
99,KODEX 단기채권,102360.0,102355.0,20917.0,21411.0,NaN,NaN,NaN
100,팬오션,3940.0,4050.0,534569.0,21062.0,44542.0,15546.0,2100.0

In [222]:
naverfin.shape

(1557, 8)

In [267]:
naverfin['myRoe'] = naverfin['영업이익']/(naverfin['자산총계']-naverfin['부채총계'])

In [269]:
naverfin[80:100]

,종목명,현재가,시가,상장주식수,시가총액,자산총계,부채총계,영업이익,myRoe
N,,,,,,,,,
81,한화솔루션,17200.0,17400.0,159864.0,27497.0,156811.0,98753.0,3783.0,0.065159
82,쌍용양회,5400.0,5480.0,503860.0,27208.0,33288.0,15263.0,2284.0,0.126713
83,삼성엔지니어링,13650.0,13800.0,196000.0,26754.0,45452.0,32424.0,3855.0,0.295901
84,휠라홀딩스,43800.0,43700.0,60752.0,26609.0,37702.0,19693.0,4707.0,0.261369
85,CJ,91100.0,92300.0,29177.0,26580.0,403814.0,257663.0,15092.0,0.103263
86,BGF리테일,151500.0,156500.0,17284.0,26185.0,21724.0,15498.0,1966.0,0.315773
87,롯데쇼핑,92300.0,94500.0,28289.0,26111.0,339726.0,220709.0,4279.0,0.035953
88,하이트진로,37150.0,38050.0,70134.0,26055.0,32709.0,22377.0,882.0,0.085366
89,한국항공우주,26600.0,27200.0,97475.0,25928.0,43671.0,31840.0,2756.0,0.232947
90,현대차2우B,71000.0,69200.0,36485.0,25905.0,NaN,NaN,NaN,NaN
91,신세계,251000.0,256500.0,9845.0,24711.0,130185.0,75034.0,4678.0,0.084822
92,금호석유,77900.0,78800.0,30468.0,23734.0,45380.0,19085.0,3678.0,0.139875
93,GS건설,29250.0,29850.0,80098.0,23429.0,131712.0,90282.0,7673.0,0.185204
94,현대해상,26000.0,26450.0,89400.0,23244.0,463938.0,418834.0,3953.0,0.087642
95,한미사이언스,34200.0,33500.0,66011.0,22576.0,9108.0,2651.0,380.0,0.058851
96,메리츠증권,3580.0,3720.0,617311.0,22100.0,381099.0,340907.0,6799.0,0.169163
97,SKC,58400.0,59300.0,37535.0,21920.0,39730.0,22466.0,1551.0,0.089840
98,일진머티리얼즈,47450.0,48400.0,46111.0,21880.0,10369.0,2127.0,469.0,0.056904
99,KODEX 단기채권,102360.0,102355.0,20917.0,21411.0,NaN,NaN,NaN,NaN
100,팬오션,3940.0,4050.0,534569.0,21062.0,44542.0,15546.0,2100.0,0.072424

In [271]:
top_roe = naverfin.sort_values(by=['myRoe'], ascending=False)

In [272]:
top_roe

,종목명,현재가,시가,상장주식수,시가총액,자산총계,부채총계,영업이익,myRoe
N,,,,,,,,,
1007,키위미디어그룹,150.0,0.0,197285.0,296.0,568.0,663.0,-108.0,1.136842
251,효성티앤씨,132500.0,133000.0,4328.0,5734.0,32243.0,26414.0,3229.0,0.553954
44,코웨이,73300.0,74100.0,73800.0,54095.0,28550.0,17778.0,4583.0,0.425455
318,효성첨단소재,86400.0,88800.0,4480.0,3871.0,25311.0,21257.0,1583.0,0.390479
550,고려개발,10000.0,9700.0,15219.0,1522.0,6134.0,4444.0,631.0,0.373373
829,세하,2175.0,2150.0,29563.0,643.0,1878.0,1499.0,141.0,0.372032
1036,에이리츠,6840.0,6530.0,3793.0,259.0,921.0,602.0,111.0,0.347962
272,한진중공업,5950.0,6020.0,83274.0,4955.0,24702.0,22252.0,838.0,0.342041
877,티에이치엔,2895.0,2990.0,18000.0,521.0,2654.0,2024.0,215.0,0.341270
328,효성화학,115000.0,116000.0,3190.0,3669.0,20635.0,16088.0,1539.0,0.338465
66,호텔신라,83300.0,84500.0,39248.0,32694.0,35273.0,26077.0,2959.0,0.321770
86,BGF리테일,151500.0,156500.0,17284.0,26185.0,21724.0,15498.0,1966.0,0.315773
341,삼호,23500.0,22500.0,15180.0,3567.0,8517.0,3939.0,1430.0,0.312363
121,F&F,102500.0,100000.0,15400.0,15785.0,6844.0,2007.0,1507.0,0.311557
911,동원수산,9710.0,9600.0,4654.0,452.0,987.0,478.0,151.0,0.296660
83,삼성엔지니어링,13650.0,13800.0,196000.0,26754.0,45452.0,32424.0,3855.0,0.295901
374,진흥기업,2085.0,2095.0,145472.0,3033.0,3258.0,2284.0,280.0,0.287474
142,DB하이텍,30650.0,30800.0,44399.0,13608.0,10889.0,4442.0,1813.0,0.281216
157,지누스,79000.0,80900.0,14407.0,11381.0,7551.0,3809.0,1039.0,0.277659
11,LG생활건강,1379000.0,1415000.0,15618.0,215375.0,64937.0,22566.0,11764.0,0.277643
731,한창,2550.0,2610.0,34790.0,887.0,918.0,651.0,74.0,0.277154
698,웅진,1235.0,1235.0,79378.0,980.0,29110.0,26366.0,752.0,0.274052
188,삼양식품,121000.0,123500.0,7533.0,9115.0,4704.0,1827.0,783.0,0.272158
549,계룡건설,17050.0,17600.0,8931.0,1523.0,20067.0,15041.0,1359.0,0.270394
428,코오롱글로벌,9270.0,9410.0,25210.0,2337.0,22181.0,17504.0,1256.0,0.268548
754,시디즈,42000.0,42000.0,2000.0,840.0,671.0,350.0,86.0,0.267913
189,쿠쿠홈시스,40300.0,40000.0,22437.0,9042.0,6266.0,1688.0,1206.0,0.263434
351,한국쉘석유,264000.0,265000.0,1300.0,3432.0,1411.0,432.0,257.0,0.262513
84,휠라홀딩스,43800.0,43700.0,60752.0,26609.0,37702.0,19693.0,4707.0,0.261369
619,한라,3180.0,3245.0,38875.0,1236.0,15882.0,13271.0,677.0,0.259288
...,...,...,...,...,...,...,...,...,...
1528,신원우,39200.0,38750.0,91.0,36.0,NaN,NaN,NaN,NaN
1529,KBSTAR 코스닥150선물인버스,6390.0,6385.0,550.0,35.0,NaN,NaN,NaN,NaN
1530,유유제약2우B,21400.0,21200.0,164.0,35.0,NaN,NaN,NaN,NaN
1531,TIGER 은행,6040.0,6130.0,580.0,35.0,NaN,NaN,NaN,NaN
1532,TIGER 200 산업재,4275.0,4390.0,800.0,34.0,NaN,NaN,NaN,NaN
1533,노루홀딩스우,18250.0,18300.0,185.0,34.0,NaN,NaN,NaN,NaN
1534,마이티 코스피고배당,10165.0,10170.0,330.0,34.0,NaN,NaN,NaN,NaN
1535,KBSTAR 수출주,8360.0,8380.0,400.0,33.0,NaN,NaN,NaN,NaN
1536,KBSTAR 팔라듐선물인버스(H),6475.0,6515.0,500.0,32.0,NaN,NaN,NaN,NaN
1537,동양우,5170.0,5210.0,618.0,32.0,NaN,NaN,NaN,NaN
1538,동양2우B,10350.0,10000.0,309.0,32.0,NaN,NaN,NaN,NaN
1539,KBSTAR 200커뮤니케이션서비스,13225.0,13125.0,240.0,32.0,NaN,NaN,NaN,NaN
1540,KBSTAR 200중공업,7915.0,7965.0,400.0,32.0,NaN,NaN,NaN,NaN
1541,ARIRANG KRX300헬스케어,11575.0,11615.0,260.0,30.0,NaN,NaN,NaN,NaN
1542,파워 스마트밸류,11790.0,11985.0,250.0,29.0,NaN,NaN,NaN,NaN
1543,KBSTAR 미국장기국채선물인버스2X(합성 H),5860.0,6000.0,500.0,29.0,NaN,NaN,NaN,NaN
1544,TIGER 대만TAIEX선물(H),14630.0,14700.0,200.0,29.0,NaN,NaN,NaN,NaN
1545,KBSTAR 중소형모멘텀로우볼,8320.0,8425.0,350.0,29.0,NaN,NaN,NaN,NaN
1546,동양3우B,31050.0,30900.0,90.0,28.0,NaN,NaN,NaN,NaN
1547,KBSTAR 200경기소비재,7710.0,7745.0,360.0,28.0,NaN,NaN,NaN,NaN
1548,KINDEX 필리핀MSCI(합성),13420.0,13410.0,200.0,27.0,NaN,NaN,NaN,NaN
1549,TIGER 금속선물(H),4385.0,4365.0,600.0,26.0,NaN,NaN,NaN,NaN
1550,KBSTAR 200철강소재,5840.0,5875.0,440.0,26.0,NaN,NaN,NaN,NaN
1551,KBSTAR 200에너지화학,7785.0,7900.0,320.0,25.0,NaN,NaN,NaN,NaN
1552,KBSTAR 200건설,8370.0,8485.0,260.0,22.0,NaN,NaN,NaN,NaN
1553,TREX 중소형가치,6735.0,6790.0,300.0,20.0,NaN,NaN,NaN,NaN
1554,KBSTAR 200금융,6960.0,7060.0,280.0,19.0,NaN,NaN,NaN,NaN
1555,TIGER 원유선물인버스(H),12010.0,11935.0,150.0,18.0,NaN,NaN,NaN,NaN
1556,TIGER 코스닥150로우볼,12540.0,12540.0,140.0,18.0,NaN,NaN,NaN,NaN
1557,KBSTAR 200산업재,7820.0,7935.0,140.0,11.0,NaN,NaN,NaN,NaN